### PR TITLE
Add support for python 3.11 + 3.12

### PR DESCRIPTION
**Pull request by angvp**
I ran the test suite and test couple of cases and it worked out of the box, worth to bump the python version as well :)

### CODE REVIEW

**Comment by DimitriPapadopoulos** [comment]
Perhaps add Python 3.12?

**Comment by angvp** [comment]
@martinblech @DimitriPapadopoulos Updated, test suite ran properly

```
tox -e py312                                                                                                                             xmltodict
.pkg: _optional_hooks> python /Users/angvp/work/xmltodict/venv/lib/python3.12/site-packages/pyproject_api/_backend.py True setuptools.build_meta __legacy__
.pkg: get_requires_for_build_sdist> python /Users/angvp/work/xmltodict/venv/lib/python3.12/site-packages/pyproject_api/_backend.py True setuptools.build_meta __legacy__
.pkg: get_requires_for_build_wheel> python /Users/angvp/work/xmltodict/venv/lib/python3.12/site-packages/pyproject_api/_backend.py True setuptools.build_meta __legacy__
.pkg: prepare_metadata_for_build_wheel> python /Users/angvp/work/xmltodict/venv/lib/python3.12/site-packages/pyproject_api/_backend.py True setuptools.build_meta __legacy__
.pkg: build_sdist> python /Users/angvp/work/xmltodict/venv/lib/python3.12/site-packages/pyproject_api/_backend.py True setuptools.build_meta __legacy__
py312: install_package> python -I -m pip install --force-reinstall --no-deps /Users/angvp/work/xmltodict/.tox/.tmp/package/3/xmltodict-0.13.0.tar.gz
py312: commands[0]> nose2 --coverage=xmltodict.py
............................................................
----------------------------------------------------------------------
Ran 60 tests in 0.002s

OK
  py312: OK (2.84=setup[2.77]+cmd[0.07] seconds)
  congratulations :) (2.89 seconds)
```

**Comment by angvp** [comment]
I just realized this PR had his first birthday ! :) ping @martinblech

**Comment by DimitriPapadopoulos** [comment]
You may add Python 3.13 in a few days :smile:

**Comment by martinblech** [comment]
Thank you!

**Pull request merged**
