### PR TITLE
Map attributes to unicode

### LINKED ISSUE #86: AttributeError: 'int' object has no attribute 'replace'
Hi,

If we try to `xmldict.unparse` the following dict it will fail:

```
{'MessageData': {
    '@infotype': 0,
    '#text': '08',
}}
```

```
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/tmp/xmltodictest/lib/python2.7/site-packages/xmltodict.py", line 333, in unparse
    **kwargs)
  File "/tmp/xmltodictest/lib/python2.7/site-packages/xmltodict.py", line 296, in _emit
    pretty, newl, indent)
  File "/tmp/xmltodictest/lib/python2.7/site-packages/xmltodict.py", line 290, in _emit
    content_handler.startElement(key, AttributesImpl(attrs))
  File "/usr/lib64/python2.7/xml/sax/saxutils.py", line 159, in startElement
    self._write(u' %s=%s' % (name, quoteattr(value)))
  File "/usr/lib64/python2.7/xml/sax/saxutils.py", line 66, in quoteattr
    data = escape(data, entities)
  File "/usr/lib64/python2.7/xml/sax/saxutils.py", line 32, in escape
    data = data.replace("&", "&amp;")
AttributeError: 'int' object has no attribute 'replace'
```

It's important that infotype is an attribute. It will work fine if an integer is a text node. 

**0.9.2**

### PR DESCRIPTION
**Pull request by centralniak**
Fixes #86

### CODE REVIEW

**Comment by centralniak** [comment]
@martinblech If you could please first merge #96 so I could rebase over it? 

I believe then the failing job would turn green.

**Comment by martinblech** [comment]
@centralniak you can rebase now

**Comment by centralniak** [comment]
Thank you. Looks I need to work a little bit more on this to resolve the Jython job failing. Will keep you posted.

**Comment by centralniak** [comment]
It appears to me that Jython implementation of `ordereddict` might be broken - in fact it just mirrors `dict` and does not retain the order.

My proposal is to just skip this one particular test in Jython build.

https://travis-ci.org/martinblech/xmltodict/jobs/58614651#L415-L420

**Comment by martinblech** [comment]
I recently updated the Travis CI configuration to use the latest stable Jython release (2.7). Would you like to rebase and give it a try, @centralniak ?

**Comment by martinblech** [comment]
Merged in df80377347259d434dbe3b86d3efcf27b16198ce. Thanks for the contribution!

**Comment by centralniak** [comment]
You're welcome :-)

**Pull request closed without merging**
