### PR TITLE
correctly unparse booleans

### PR DESCRIPTION
**Pull request by Pertempto**
This fixes issue #179.

### CODE REVIEW

**Comment by Pertempto** [comment]
Sure!

**Comment by Pertempto** [comment]
I'm not very familiar with test cases though. Do I just add a function to the bottom of tests/test_dicttoxml.py that tests that the unparsing is working fine for booleans?

**Comment by Pertempto** [comment]
Did I do it right or do I need to change something?

**Comment by Pertempto** [comment]
Fixed issue #162.

**Comment by martinblech** [comment]
Thank you!

**Pull request merged**
