### PR TITLE
Switch namespace separator from colon to pipe (fixes #289)

### LINKED ISSUE #289: Namespace separator ':' incompatible with Expat >=2.4.5 <2.4.7 security fixes
Hi @martinblech,

it was [brought to my attention](https://github.com/NixOS/nixpkgs/pull/161090#issuecomment-1049540649) that xmltodict and Expat >=2.4.5 are not compatible. The incompatibility has two halves:
- xmltodict is using `:` (colon) for a namespace separator at multiple places, for instance:
  ```console
  # git --no-pager grep "namespace_separator='"
  xmltodict.py:                 namespace_separator=':',
  xmltodict.py:          namespace_separator=':', disable_entities=True, process_comments=False, **kwargs):
  xmltodict.py:          namespace_separator=':',
  ```
- Expat disallows use of namespace separator characters in `xmlns` attribute values for security since 2.4.5 and PR https://github.com/libexpat/libexpat/pull/561.

The [API docs of `XML_ParserCreateNS`](https://libexpat.github.io/doc/api/latest/#XML_ParserCreateNS) say:

> This means that you should pick a character for sep that can't be part of an URI.

Colon can appear in a URI (RFC 3986), so a colon cannot be used as a namespace separator or there will be false positives. Use of `" "` (space) or `"\n"` (line feed) would work.

Would you be up for picking a different character for a namespace separator?

Thanks and best, Sebastian

CC https://github.com/libwbxml/libwbxml/issues/76
CC https://github.com/libexpat/libexpat/issues/572#issuecomment-1050119036

### PR DESCRIPTION
**Pull request by hartwork**
Fixes #289

### CODE REVIEW

**Comment by exxamalte** [comment]
It should probably be mentioned that this fix does indeed break all parsers that use this library and that parse XML with multiple namespaces, and that have so far relied on the default namespace separator.

**Comment by hartwork** [comment]
@exxamalte that's a fair point

**Comment by sktzofrenic** [comment]
> It should probably be mentioned that this fix does indeed break all parsers that use this library and that parse XML with multiple namespaces, and that have so far relied on the default namespace separator.

Leaving it as is breaks many more projects though. 

Thank you @hartwork for doing the legwork on this.

**Comment by hartwork** [comment]
Closing in favor of https://github.com/libexpat/libexpat/pull/577 .

**Pull request closed without merging**
