### PR TITLE
Ordered children and short tags

### PR DESCRIPTION
**Pull request by lindsay-stevens**
I know I've got some merge conflicts but I thought I'd open this PR to see if the additions are of interest. If so let me know and I'll resolve them.

The added features are:
- preserve element order. During parse, the order is stored as an element attribute named __order__. During unparse, the __order__ attribute is removed from the output. Tests demonstrate round-tripping to read/write identical documents. The kwargs to enable this feature default to "off" since it's more of an XHTML thing.
- short element tags. Similar to #132, but done in such a way as to be compatible with all target Pythons listed in tox, instead of 3.2+ only.

### CODE REVIEW

**Comment by chesstrian** [comment]
@lindsay-stevens Does this preserve order on `unparse`?.

**Comment by lindsay-stevens** [comment]
Yes, there's some tests included in the PR demonstrating equal documents on
a parse/unparse round trip.

**Comment by javadev** [comment]
This branch has conflicts that must be resolved

**Comment by javadev** [comment]
```xml
<?xml version="1.0" encoding="UTF-8"?>
<a>
   <b>
      <d>1</d>
      <d>2</d>
   </b>
   <c>
      <f>5</f>
      <f>6</f>
   </c>
   <b>
      <e>test</e>
   </b>
   <c>
      <g>a</g>
      <g>b</g>
   </c>
</a>
```
may be converted to
```json
{
  "a": {
    "b": [
      {
        "d": [
          "1",
          "2"
        ]
      },
      {
        "#item": {
          "c": {
            "f": [
              "5",
              "6"
            ]
          }
        }
      },
      {
        "e": "test"
      }
    ],
    "c": {
      "g": [
        "a",
        "b"
      ]
    }
  }
}
```

**Pull request closed without merging**
