### PR TITLE
Moved the data from string to list

### PR DESCRIPTION
**Pull request by bharel**
Moving the data from string to list causes a significant speed and
memory improvement noticed mostly in large XML files. Appending to a
list is more efficient than reconstructing a string.

The speed improvement seen by me was up to 1000x faster on xml files weighting 150MBs or more.

### CODE REVIEW

**Comment by martinblech** [comment]
Thank you for the contribution! The change looks good to me. Do you have any benchmarks regarding the speed and memory improvements?

**Comment by bharel** [comment]
I took a simple xml file:
<?xml version="1.0"?>
<test>
the letter a 400,000,000 times
</test>

xmltodict is the current one while xmltodict_2 is after the small patch.

python -m timeit -s "from xmltodict_2 import parse; xml = open('largexml.xml').read()" "res = parse(xml)"
10 loops, best of 3: 2.27 sec per loop

python -m timeit -s "from xmltodict import parse; xml = open('largexml.xml').read()" "res = parse(xml)"

The first one (post-patch) took 2.27 per loop (22 seconds overall).
The second one (pre-patch) is running till this very moment and taking all of my memory.

In the current status, xmltodict took ~1.7GB of memory topping at 1.9. After my patch it took around ~630MB top.
image

I'll update tomorrow morning regarding if it finished or not.

**Comment by kmonsoor** [comment]
@bharel  imo, plz consider adding some relevant comments inline to make non-confusing. 
Because many programmers would guess about using a **String ** here. thanks.

**Comment by bharel** [comment]
I disagree with you due to the fact that data is initialized as a list a
few times throughout the code and uses the ".append" attribute. Commenting
that data is a list on the definition of "data = []" is redundant I
believe. The only place data returns to be a string is in a temporary
variable inside an inner function.

**Comment by kmonsoor** [comment]
> Commenting that data is a list on the definition of "data = []" is redundant

i agree. 

however, i meant commenting for **why** "data is a list", but not a string would be helpful.

**Comment by martinblech** [comment]
Wow, thanks for the benchmark @bharel, it's a simple change that makes a huge difference!

**Comment by martinblech** [comment]
@kmonsoor There's no need for documentation, it's an internal data structure change that is completely transparent for the user. You still get a str in the end, the list is only used internally.

**Pull request merged**
